# Generated by Django 5.0.1 on 2024-02-04 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date submitted')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.question')),
            ],
        ),
    ]
